#!/usr/bin/env python3
"""Generate derived files from tools.toml (the single source of truth).

Outputs:
  README.md         human-readable + picker-oriented doc (grouped, with `when`)
  Brewfile          `brew bundle` manifest (baseline + full, commented)
  apt-packages.sh   apt install script (baseline + full, commented)
  tools.json        machine-readable index for an agent/picker
"""
import json
import re
import sys
import tomllib
from pathlib import Path

HERE = Path(__file__).parent
SRC = HERE / "tools.toml"

AVAIL_ORDER = {"posix": 0, "pkg": 1, "heavy": 2}
AVAIL_LABEL = {
    "posix": "preinstalled",
    "pkg": "one package",
    "heavy": "heavy / model",
}


def load():
    with SRC.open("rb") as f:
        return tomllib.load(f)["tool"]


def is_real_pkg(field: str | None) -> bool:
    """A usable package name (not a '# do it another way' note or missing)."""
    return bool(field) and not field.strip().startswith("#")


# ---------------------------------------------------------------- README.md
def gen_readme(tools):
    by_role = {}
    for t in tools:
        by_role.setdefault(t["role"], []).append(t)

    lines = []
    lines.append("# Text-processing pipeline toolbox\n")
    lines.append(
        "Single source of truth: **`tools.toml`**. This file and the install "
        "manifests are generated by `generate.py` — edit the TOML, then re-run "
        "`python3 generate.py`.\n"
    )
    lines.append("## How to read this\n")
    lines.append(
        "- **role** — what the tool does (primary picker axis).\n"
        "- **group** — redundancy cluster: pick **at most one** tool per group "
        "for a given job. The picker should prefer lower install cost within a group.\n"
        "- **avail** — `posix` (preinstalled) · `pkg` (one brew/apt install) · "
        "`heavy` (large dep / model download).\n"
        "- **★** marks the curated **baseline** set (install once; covers most pipelines).\n"
        "- **when** — when to reach for it vs. its group-mates.\n"
    )

    # Baseline quick-list
    base = [t for t in tools if t.get("baseline")]
    lines.append("## Baseline toolbox (install once)\n")
    lines.append(
        "These cover ~90% of pipelines with minimal redundancy:\n\n"
        + ", ".join(f"`{t['name'].split(' ')[0]}`" for t in base)
        + "\n"
    )

    # Redundancy groups that actually have a choice to make
    multi = {}
    for t in tools:
        multi.setdefault(t["group"], []).append(t["name"])
    contested = {g: ns for g, ns in multi.items() if len(ns) > 1 and g != "unique"}
    lines.append("## Redundancy groups (choose one per job)\n")
    for g in sorted(contested):
        names = ", ".join(f"`{n.split(' ')[0]}`" for n in contested[g])
        lines.append(f"- **{g}**: {names}")
    lines.append("")

    # Full index by role
    lines.append("## Full index by role\n")
    for role in sorted(by_role):
        lines.append(f"### {role}\n")
        group = sorted(
            by_role[role], key=lambda t: (AVAIL_ORDER.get(t["avail"], 9), t["name"])
        )
        for t in group:
            star = "★ " if t.get("baseline") else ""
            inst = []
            if is_real_pkg(t.get("brew")):
                inst.append(f"brew: `{t['brew']}`")
            if is_real_pkg(t.get("apt")):
                inst.append(f"apt: `{t['apt']}`")
            note = ""
            if not is_real_pkg(t.get("brew")) and t.get("brew"):
                note = f" · {t['brew'].lstrip('# ').strip()}"
            elif not is_real_pkg(t.get("apt")) and t.get("apt"):
                note = f" · {t['apt'].lstrip('# ').strip()}"
            inst_str = " · ".join(inst) if inst else (note.lstrip(" ·") or "—")
            lines.append(
                f"- {star}**{t['name']}** "
                f"[{AVAIL_LABEL.get(t['avail'], t['avail'])}, group: `{t['group']}`] — "
                f"{t.get('when', '').strip()}\n  - {inst_str}"
            )
        lines.append("")

    (HERE / "README.md").write_text("\n".join(lines))


# ---------------------------------------------------------------- Brewfile
def gen_brewfile(tools):
    def brew_name(t):
        return t["brew"] if is_real_pkg(t.get("brew")) else None

    base = [t for t in tools if t.get("baseline") and brew_name(t)]
    rest = [t for t in tools if not t.get("baseline") and brew_name(t)]
    noted = [t for t in tools if t.get("brew") and not is_real_pkg(t.get("brew"))]

    seen = set()
    out = ["# Brewfile — generated from tools.toml. Run: brew bundle",
           "#", "# === Baseline (install once) ==="]
    for t in base:
        f = t["brew"]
        if f in seen:
            continue
        seen.add(f)
        out.append(f'brew "{f}"  # {t["name"]}')
    out += ["", "# === Full set (uncomment as needed) ==="]
    for t in rest:
        f = t["brew"]
        if f in seen:
            continue
        seen.add(f)
        out.append(f'# brew "{f}"  # {t["name"]}')
    if noted:
        out += ["", "# === Not via brew formula — install another way ==="]
        for t in noted:
            out.append(f'# {t["name"]}: {t["brew"].lstrip("# ").strip()}')
    (HERE / "Brewfile").write_text("\n".join(out) + "\n")


# ---------------------------------------------------------------- apt script
def gen_apt(tools):
    def apt_name(t):
        return t["apt"] if is_real_pkg(t.get("apt")) else None

    base = [t for t in tools if t.get("baseline") and apt_name(t)]
    rest = [t for t in tools if not t.get("baseline") and apt_name(t)]
    noted = [t for t in tools if t.get("apt") and not is_real_pkg(t.get("apt"))]

    def dedup(ts):
        seen, out = set(), []
        for t in ts:
            p = t["apt"]
            if p in seen:
                continue
            seen.add(p)
            out.append((p, t["name"]))
        return out

    lines = ["#!/usr/bin/env bash",
             "# apt install script — generated from tools.toml.",
             "# Usage: bash apt-packages.sh   (review before running)",
             "set -euo pipefail", "", "sudo apt-get update", "",
             "# === Baseline (install once) ==="]
    base_pkgs = dedup(base)
    lines.append("sudo apt-get install -y \\")
    for i, (p, name) in enumerate(base_pkgs):
        tail = " \\" if i < len(base_pkgs) - 1 else ""
        lines.append(f"  {p}{tail}")          # no trailing comment after backslash
    lines += ["", "# === Full set (uncomment the block to add) ===", "# sudo apt-get install -y \\"]
    rest_pkgs = dedup(rest)
    for i, (p, name) in enumerate(rest_pkgs):
        tail = " \\" if i < len(rest_pkgs) - 1 else ""
        lines.append(f"#   {p}{tail}")
    if noted:
        lines += ["", "# === Not in apt — install another way ==="]
        for t in noted:
            lines.append(f'# {t["name"]}: {t["apt"].lstrip("# ").strip()}')
    (HERE / "apt-packages.sh").write_text("\n".join(lines) + "\n")


# ---------------------------------------------------------------- tools.json
def gen_json(tools):
    (HERE / "tools.json").write_text(json.dumps(tools, indent=2))


def main():
    tools = load()
    gen_readme(tools)
    gen_brewfile(tools)
    gen_apt(tools)
    gen_json(tools)
    print(f"Generated from {len(tools)} tools: README.md, Brewfile, apt-packages.sh, tools.json")


if __name__ == "__main__":
    main()
